# Server
server.port=8080

# Local Database
spring.datasource.url=jdbc:postgresql://localhost:5432/teamtaskers_db
spring.datasource.username=teamtaskers_user
spring.datasource.password=Teamtaskers@123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=teamtaskers-secret-key-123456789
jwt.expiration=86400000
