spring.application.name=teamtaskers

# Profile switching (default = dev)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Server Port (Render injects PORT automatically)
server.port=${PORT:8080}
